from enum import Enum, unique

@unique
class TokenList(Enum):
    # Keywords
    kw_nil = 'nil'
    kw_for = 'for'
    kw_in = 'in'
    kw_continue = 'continue'
    kw_break = 'break'
    kw_if = 'if'
    kw_else = 'else'
    kw_not = 'not'
    kw_or = 'or'
    kw_xor = 'xor'
    kw_and = 'and'
    kw_true = 'true'
    kw_false = 'false'
    kw_while = 'while'
    kw_return = 'return'
    kw_scope = 'scope' #not yet implemented
    # Types
    pt_let = 'let'
    pt_bool = 'bool'
    pt_u8 = 'u8'
    pt_u16 = 'u16'
    pt_u32 = 'u32'
    pt_u64 = 'u64'
    pt_i8 = 'i8'
    pt_i16 = 'i16'
    pt_i32 = 'i32'
    pt_i64 = 'i64'  
    pt_float = 'f32'
    pt_double = 'f64'
    # Operators
    sym_not = '!'
    sym_not_equal = '!='
    sym_at = '@'
    sym_hash = '#'
    sym_dollar = '$'
    sym_remainder = '%'
    sym_assign_remain = '%='
    sym_xor = '^'
    sym_assign_xor = '^='
    sym_and = '&'
    sym_assign_and = '&='
    sym_asterisk = '*'
    sym_assign_multiply = '*='
    sym_paren_open = '('
    sym_paren_close = ')'
    sym_minus = '-'
    sym_minus_one = '--'
    sym_assign_subtract = '-='
    sym_add = '+'
    sym_plus_one = '++'
    sym_assign_add = '+='
    sym_assign = '='
    sym_equal = '=='
    sym_brace_open = '{'
    sym_brace_close = '}'
    sym_bracket_open = '['
    sym_bracket_close = ']'
    sym_or = '|'
    sym_assign_or = '|='
    sym_divide = '/'
    sym_assign_divide = '/='
    sym_semicolon = ';'
    sym_less = '<'
    sym_less_equal = '<='
    sym_shift_left = '<<'
    sym_greater = '>'
    sym_greater_equal = '>='
    sym_shift_right = '>>'
    sym_comma = ','

    identifier = 'Identifier'
    # Literals
    str_literal = 'StringLiteral'
    float_literal = 'FloatLiteral'
    int_literal = 'IntegerLiteral'
